# 张量简介


In [2]:
import tensorflow as tf 
import numpy as np

## 张量的数据类型为Dtype

所有张量都是不可变的，只能创建新的张量

In [3]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
rank_2_tensor = tf.constant([[1, 2], 
                             [3, 4], 
                             [5, 6]])
print(rank_2_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [11]:
rank_3_tensor = tf.constant([
    [
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
[
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]
],
[
    [20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]
]   
]  
)
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [12]:
np.array(rank_2_tensor)

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [13]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [15]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1,1]]) 
print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [16]:
print(a + b, "\n")
print(a * b, "\n")
print(a @ b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [20]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
# find the largest value
print(tf.reduce_max(c))
# find the index of the largest value
print(tf.math.argmax(c))
#compute the softmax
print(tf.nn.softmax(c))

print(c[1, 0])  

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)


In [21]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [22]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [23]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

张量形状 
形状 张量每个轴的长度
秩 张量轴数 标量秩为0，矢量秩为1， 矩阵秩为2
轴或维度 
大小：张量的总箱数，形状质量元素的乘积

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [25]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [27]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>